#%RAML 1.0
title: FOLIO Open Access API
baseUri: /oa
version: 1.0

types:
  AppSetting:
    type: object 
    properties: 
      id: String
      section: String
      key: String
      settingType: String
      vocab: String
      defValue: String
      value: String
    examples:
      stringSetting:
        id: 1234
        section: NCIP
        key: EndpointURL
        settingType: String
        vocab: null
        defValue: null
        value: http://some.host/some/path
  Funding:
  TitleInstance:
  Work:
  Party:
  ChecklistGroup:
  Correspondence:
  RefdataCategory:


traits:
  simpleLookupService:
    description: |
      Simple lookup service is a trait that supports the default FOLIO UX by providing a simple search box and a field to use along with a more complex filter expression language
    examples:
      AgreementSearch: |
        filters=agreementStatus.value==active%7C%7CagreementStatus.value==draft%7C%7CagreementStatus.value==in_negotiation%7C%7CagreementStatus.value==requested&filters=tags.value==urgent&sort=name;asc&stats=true&perPage=100&offset=0
        
    queryParameters:
      filters:
        description: |
          A DSL for filtering understanding logical connectives && ||, comparisons =i= == != 
        examples:
          "Agreements where agreement status value is active": |
             filters=agreementStatus.value==active
          "Agreements where agreement status value is active OR status.value is draft": |
             filters=agreementStatus.value==active||agreementStatus.value==draft
      sort:
        description: List of fields/order specifiers
        examples:
          "Sort by name ascending": |
            sort=name;asc
      perPage:
       description: Maximum number of objects to return
      match:
       description: Field to use for term search
      term:
        description: Term to search for
      offset:
        description: Offset for paging
      stats:
        description: Wrap the search result in an outer object that reports hit counts and other search metadata

resourceTypes:
  KIWTResourceCollection:
    description: General REST api for instances of <<typeName>>
    get:
      description: Search over all current instances of this resource class
      is: [simpleLookupService]
      responses:
        200:
          application/json:
            type: <<resourcePathName|!singularize|!uppercamelcase>>[]
    post:
      description: Create a new instance of the Resource Class
      type: <<resourcePathName|!singularize|!uppercamelcase>>
      responses:
        201:
          body:
            application/json:
              type: <<typeName>>
  KIWTResourceItem:
    put:
      description: Update an existing instance
      type:  <<resourcePathName|!singularize|!uppercamelcase>>
    get:
      description: Get a specific instance
      type:  <<resourcePathName|!singularize|!uppercamelcase>>

/refdata:
  /{refdata_category}:
    displayName: Access a specific category
    type: { KIWTResourceCollection: { "typeName": "RefdataCategory" } }

/settings:
  /appSettings:
    type: { KIWTResourceCollection: { "typeName": "AppSetting" } }
    description: Application settings

/fundings:
  type: { KIWTResourceCollection: { "typeName": "Funding" } }
  description: Application settings

/titleInstances:
  type: { KIWTResourceCollection: { "typeName": "TitleInstance" } }
  description: An Instance in the FRBR/Bibframe sense - an individually identifable specific appearence of a work made concrete in some medium/form/edition

/works:
  type: { KIWTResourceCollection: { "typeName": "Work" } }
  description: A work in the FRBR/Bibframe Sense - E.G. "Nature" as opposed to the print or electronic instances of Nature, or "Brain of the Firm" a book but not a specific edition of that book

/party:
  type: { KIWTResourceCollection: { "typeName": "Party" } }
  description: An individual or institution participating in an OA publication request - possibly NOT a member of THIS institution and possibly without a login

/checklistGroup:
  type: { KIWTResourceCollection: { "typeName": "ChecklistGroup" } }
  description:

/correspondence:
  type: { KIWTResourceCollection: { "typeName": "Correspondence" } }
  description:


