name: Grails CI
on:
  push:
    branches:
      - master 
      - modoa-4
  pull_request:
    branches:
      - master 
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./service
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: actions/cache@v1 
        with:
          path: ~/.gradle/caches  
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }} 
          restore-keys: |
            ${{ runner.os }}-gradle-


      - name: Start containers
        run: |
          cd ../tools/testing
          docker-compose -f "docker-compose.yml" up -d

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Stop containers
        run: |
          cd ../tools/testing
          docker-compose -f "docker-compose.yml" down -v

